import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { getPlaiceholder } from "plaiceholder";
import { projects } from "../src/data/projects";

const PUBLIC_DIR = path.join(process.cwd(), "public");
const OUTPUT_FILE = path.join(
	process.cwd(),
	"src",
	"data",
	"generated",
	"image-placeholders.ts"
);

async function generateFor(imagePath: string): Promise<[string, string]> {
	const absolute = path.join(PUBLIC_DIR, imagePath);
	let buffer: Buffer;
	try {
		buffer = await readFile(absolute);
	} catch (err) {
		throw new Error(
			`Cannot read image referenced by projects data: ${imagePath} (resolved to ${absolute}). ${(err as Error).message}`
		);
	}
	const { base64 } = await getPlaiceholder(buffer, { size: 10 });
	return [imagePath, base64];
}

async function main(): Promise<void> {
	const imagePaths = projects.map((p) => p.image);
	const entries = await Promise.all(imagePaths.map(generateFor));
	entries.sort(([a], [b]) => a.localeCompare(b));

	const body = entries
		.map(
			([key, value]) => `\t${JSON.stringify(key)}: ${JSON.stringify(value)},`
		)
		.join("\n");

	const file = `// AUTO-GENERATED by scripts/generate-image-placeholders.ts. Do not edit by hand.
// Run \`pnpm generate:placeholders\` to refresh.

export const imagePlaceholders: Record<string, string> = {
${body}
};
`;

	await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
	await writeFile(OUTPUT_FILE, file, "utf8");
	console.log(
		`Wrote ${entries.length} placeholder(s) to ${path.relative(process.cwd(), OUTPUT_FILE)}`
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
